### ISSUE TITLE
exception when accessing column that doesn't exist

### ISSUE THREAD

**Issue by nkostis** [InfluxCommunity/influxdb3-csharp#48]
### Specifications

* Client Version: 0.2.0
* InfluxDB Version: 3.x
* Platform: Windows 10

any InfluxQL query that addresses a column that doesn't exist (yet) results in exception thrown; please see below for details

### Code sample to reproduce problem

```csharp
select mean(hum) as mean_hum, mean(co2) as mean_co2 FROM environmental WHERE time > '2023-05-01T00:00:00Z' and time < '2023-06-30T00:00:00Z' and id= '835' group by time(1d)
```
in this example the column `hum` doesn't exist, the correct column is `humidity`.
The code produces the exception shown in "Actual behavior"

### Expected behavior

I would expect the behavior of InfluxQL on influx 1.X which is to return data from co2 and treat the wrong column as missing..
```
time (UTC) | mean_hum | mean_co2
2023-05-01T00:00:00Z |   | 450.27
2023-05-02T00:00:00Z |   | 590.85
[...]
```

### Actual behavior

exception thrown with message:  `Arrow primitive 'Null' is unsupported.`

and stack trace:
```
   at Apache.Arrow.Ipc.MessageSerializer.GetFieldArrowType(Field field, Field[] childFields)
   at Apache.Arrow.Ipc.MessageSerializer.FieldFromFlatbuffer(Field flatbufField, DictionaryMemo& dictionaryMemo)
   at Apache.Arrow.Ipc.MessageSerializer.GetSchema(Schema schema, DictionaryMemo& dictionaryMemo)
   at Apache.Arrow.Flight.FlightMessageSerializer.DecodeSchema(ByteBuffer schemaBuffer)
   at Apache.Arrow.Flight.Internal.RecordBatcReaderImplementation.<ReadSchema>d__8.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Apache.Arrow.Flight.Internal.RecordBatcReaderImplementation.<ReadNextRecordBatchAsync>d__9.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Apache.Arrow.Flight.FlightRecordBatchStreamReader.<MoveNext>d__12.MoveNext()
   at InfluxDB3.Client.Internal.FlightSqlClient.<Execute>d__5.MoveNext()
   at InfluxDB3.Client.Internal.FlightSqlClient.<Execute>d__5.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at InfluxDB3.Client.InfluxDBClient.<Query>d__8.MoveNext()
   at InfluxDB3.Client.InfluxDBClient.<Query>d__8.MoveNext()
   at InfluxDB3.Client.InfluxDBClient.<Query>d__8.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Threading.Tasks.TaskAsyncEnumerableExtensions.<ToBlockingEnumerable>d__3`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Yodiwo.FEMP.CloningService.InfluxMigrators.<Influx1toInflux2>d__13.MoveNext() in C:\DEV\yodifem\uServicesSingleton\CloningService.Asp\Scratchpad\InfluxMigrators.cs:line 306
```

### Additional info

(instructed to post here by Ben Tasker)

**Comment by bednar** [comment]
Hi @nkostis,

thanks for using our client. 

@Sciator will take a look...

Best

**Comment by bednar** [comment]
Hi @nkostis,

Apologies for the delay.

I tried replicating your issue but couldn't reproduce it. Here's the data I have in my database:

```csv
Copy code
#group,false,false,false
#datatype,double,string,dateTime:RFC3339
#default,,,
,co2,location,time
,100,europe,2023-09-27T10:23:09.371636812Z
I queried the data using:
```
```csharp
Copy code
using System;
using System.Threading.Tasks;
using InfluxDB3.Client;
using InfluxDB3.Client.Query;

namespace InfluxDB3.Examples.IOx;

public class IOxExample
{
    static async Task Main(string[] args)
    {
        const string host = "https://us-east-1-1.aws.cloud2.influxdata.com";
        const string token = "my-token";
        const string database = "my-database";

        using var client = new InfluxDBClient(host: host, token: token, database: database);

        await foreach (var row in client.Query(query: "SELECT mean(hum) as mean_hum, mean(co2) as mean_co2 FROM data group by time(1d)", queryType: QueryType.InfluxQL))
        {
            Console.WriteLine(string.Join(" | ", row));
        }
    }
}
```

All seems to work correctly. Can you provide more details, maybe a simplified example or how your data is structured to help simulate the exception? Also, have you tried executing your query via the InfluxDB UI?

Best regards.

**Comment by bednar** [comment]
This PR has been closed because it has not had recent activity. Please reopen if this PR is still important to you and you want to continue with them.
